// Semente curada da Biblioteca Musical.
//
// Usada em dois lugares:
//  1. Fallback da página pública enquanto o Supabase não está configurado.
//  2. scripts/seed-showcase.ts — insere estas músicas na sua conta (vitrine).
//
// O `id` aqui é um slug legível; ao semear no banco, o script troca por uuids
// e resolve prerequisites/nextSongs (que também são slugs) para os uuids reais.

import type { Song } from './data'

export const SEED_SONGS: Song[] = [
  {
    id: 'trem-bala',
    title: 'Trem-Bala',
    artist: 'Ana Vilela',
    difficulty: 2,
    status: 'dominada',
    techniques: ['cantar-tocando'],
    contexts: ['mpb', 'cantar-junto', 'para-filha'],
    prerequisites: [],
    nextSongs: ['voce-e-linda', 'blackbird'],
    bestVersion: { label: 'Ana Vilela — ao vivo', url: 'https://www.youtube.com/results?search_query=ana+vilela+trem+bala+ao+vivo' },
    bestLesson: { label: 'Aula (com voz)', url: 'https://www.youtube.com/results?search_query=trem+bala+aula+violao' },
    notes: 'Quatro acordes e uma letra que a plateia certa já sabe de cor. Boa primeira música para soltar a voz enquanto a mão vai no automático.',
  },
  {
    id: 'asa-branca',
    title: 'Asa Branca',
    artist: 'Luiz Gonzaga',
    difficulty: 2,
    status: 'dominada',
    techniques: ['cantar-tocando'],
    contexts: ['mpb', 'cantar-junto'],
    prerequisites: [],
    nextSongs: ['voce-e-linda'],
    bestVersion: { label: 'Luiz Gonzaga', url: 'https://www.youtube.com/results?search_query=luiz+gonzaga+asa+branca' },
    bestLesson: { label: 'Aula', url: 'https://www.youtube.com/results?search_query=asa+branca+aula+violao' },
    notes: 'Patrimônio. Fácil de tocar, difícil de tocar com o balanço certo do baião — é aí que mora a lição.',
  },
  {
    id: 'voce-e-linda',
    title: 'Você é Linda',
    artist: 'Caetano Veloso',
    difficulty: 3,
    status: 'aprendendo',
    techniques: ['cantar-tocando', 'voicings'],
    contexts: ['mpb', 'cantar-junto', 'para-filha'],
    prerequisites: ['trem-bala'],
    nextSongs: ['garota-de-ipanema'],
    bestVersion: { label: 'Caetano Veloso', url: 'https://www.youtube.com/results?search_query=caetano+veloso+voce+e+linda' },
    bestLesson: { label: 'Aula com os acordes originais', url: 'https://www.youtube.com/results?search_query=voce+e+linda+aula+violao' },
    notes: 'Primeiro contato com acordes mais coloridos do Caetano. A troca rápida no refrão é o ponto de atenção.',
  },
  {
    id: 'here-comes-the-sun',
    title: 'Here Comes the Sun',
    artist: 'The Beatles',
    difficulty: 3,
    status: 'aprendendo',
    techniques: ['fingerstyle', 'cantar-tocando'],
    contexts: ['pop-rock', 'cantar-junto', 'para-filha', 'relaxar'],
    prerequisites: ['trem-bala'],
    nextSongs: ['blackbird'],
    bestVersion: { label: 'The Beatles (Abbey Road)', url: 'https://www.youtube.com/results?search_query=here+comes+the+sun+beatles' },
    bestLesson: { label: 'Aula com o riff e a pestana', url: 'https://www.youtube.com/results?search_query=here+comes+the+sun+guitar+lesson' },
    notes: 'O riff é o coração. Vale isolar a introdução antes de juntar com a voz. Música que ilumina qualquer sala.',
  },
  {
    id: 'dust-in-the-wind',
    title: 'Dust in the Wind',
    artist: 'Kansas',
    difficulty: 3,
    status: 'aprendendo',
    techniques: ['travis-picking', 'fingerstyle', 'independencia-mao-direita'],
    contexts: ['pop-rock', 'estudar-tecnica', 'relaxar'],
    prerequisites: [],
    nextSongs: ['blackbird', 'tears-in-heaven'],
    bestVersion: { label: 'Kansas', url: 'https://www.youtube.com/results?search_query=kansas+dust+in+the+wind' },
    bestLesson: { label: 'Aula de Travis picking', url: 'https://www.youtube.com/results?search_query=dust+in+the+wind+travis+picking+lesson' },
    notes: 'A porta de entrada do Travis picking. Devagar até o baixo alternado virar automático — depois a música se toca sozinha.',
  },
  {
    id: 'nothing-else-matters',
    title: 'Nothing Else Matters',
    artist: 'Metallica',
    difficulty: 3,
    status: 'quero-aprender',
    techniques: ['fingerstyle', 'cantar-tocando'],
    contexts: ['pop-rock', 'cantar-junto'],
    prerequisites: [],
    nextSongs: ['tears-in-heaven'],
    bestVersion: { label: 'Metallica (S&M / acústico)', url: 'https://www.youtube.com/results?search_query=metallica+nothing+else+matters+acoustic' },
    bestLesson: { label: 'Aula da introdução', url: 'https://www.youtube.com/results?search_query=nothing+else+matters+intro+lesson' },
    notes: 'A introdução em cordas soltas é um ótimo estudo de mão direita sem exigir a esquerda. Cresce bem para acompanhar cantando.',
  },
  {
    id: 'blackbird',
    title: 'Blackbird',
    artist: 'The Beatles',
    difficulty: 3,
    status: 'aprendendo',
    techniques: ['fingerstyle', 'independencia-mao-direita', 'cantar-tocando'],
    contexts: ['pop-rock', 'folk-indie', 'para-filha', 'estudar-tecnica'],
    prerequisites: ['dust-in-the-wind', 'trem-bala'],
    nextSongs: ['classical-gas', 'drifting'],
    bestVersion: { label: 'Paul McCartney', url: 'https://www.youtube.com/results?search_query=paul+mccartney+blackbird' },
    bestLesson: { label: 'Aula detalhada (mão direita)', url: 'https://www.youtube.com/results?search_query=blackbird+guitar+lesson' },
    notes: 'O primeiro grande marco: melodia e baixo dançando em oitavas. Ganha muito quando entra a voz por cima. Um divisor de águas.',
  },
  {
    id: 'tears-in-heaven',
    title: 'Tears in Heaven',
    artist: 'Eric Clapton',
    difficulty: 4,
    status: 'quero-aprender',
    techniques: ['fingerstyle', 'independencia-mao-direita', 'cantar-tocando'],
    contexts: ['pop-rock', 'relaxar', 'cantar-junto'],
    prerequisites: ['dust-in-the-wind', 'nothing-else-matters'],
    nextSongs: ['cavatina'],
    bestVersion: { label: 'Eric Clapton (Unplugged)', url: 'https://www.youtube.com/results?search_query=eric+clapton+tears+in+heaven+unplugged' },
    bestLesson: { label: 'Aula com as viradas', url: 'https://www.youtube.com/results?search_query=tears+in+heaven+guitar+lesson' },
    notes: 'As viradinhas de baixo entre os acordes são o desafio. Melodia doce, harmonia mais rica que parece.',
  },
  {
    id: 'garota-de-ipanema',
    title: 'Garota de Ipanema',
    artist: 'Tom Jobim & Vinicius de Moraes',
    difficulty: 4,
    status: 'quero-aprender',
    techniques: ['bossa-nova', 'voicings', 'cantar-tocando'],
    contexts: ['mpb', 'cantar-junto', 'estudar-tecnica'],
    prerequisites: ['voce-e-linda'],
    nextSongs: ['wave'],
    bestVersion: { label: 'João Gilberto / Tom Jobim', url: 'https://www.youtube.com/results?search_query=joao+gilberto+garota+de+ipanema' },
    bestLesson: { label: 'Aula de batida de bossa', url: 'https://www.youtube.com/results?search_query=garota+de+ipanema+batida+bossa+nova+aula' },
    notes: 'A entrada oficial na bossa. O segredo está na mão direita: o polegar marca o baixo enquanto os dedos sincopam. A ponte muda de tom — cuidado ali.',
  },
  {
    id: 'wave',
    title: 'Wave (Vou Te Contar)',
    artist: 'Tom Jobim',
    difficulty: 4,
    status: 'quero-aprender',
    techniques: ['bossa-nova', 'voicings', 'improvisacao'],
    contexts: ['mpb', 'relaxar', 'estudar-tecnica'],
    prerequisites: ['garota-de-ipanema'],
    nextSongs: [],
    bestVersion: { label: 'Tom Jobim', url: 'https://www.youtube.com/results?search_query=tom+jobim+wave' },
    bestLesson: { label: 'Aula com os voicings', url: 'https://www.youtube.com/results?search_query=wave+jobim+chords+lesson' },
    notes: 'Uma aula de harmonia sozinha. Os acordes descem cromaticamente — decorar o movimento vale mais que decorar cada forma.',
  },
  {
    id: 'classical-gas',
    title: 'Classical Gas',
    artist: 'Mason Williams',
    difficulty: 5,
    status: 'quero-aprender',
    techniques: ['fingerstyle', 'independencia-mao-direita', 'improvisacao'],
    contexts: ['estudar-tecnica', 'bosses'],
    prerequisites: ['blackbird'],
    nextSongs: [],
    bestVersion: { label: 'Mason Williams', url: 'https://www.youtube.com/results?search_query=mason+williams+classical+gas' },
    bestLesson: { label: 'Aula por partes', url: 'https://www.youtube.com/results?search_query=classical+gas+guitar+lesson' },
    notes: 'Boss de velocidade e coordenação. Estudar por seções, uma de cada vez, sem pressa de juntar tudo.',
  },
  {
    id: 'drifting',
    title: 'Drifting',
    artist: 'Andy McKee',
    difficulty: 5,
    status: 'quero-aprender',
    techniques: ['percussao', 'harmonicos', 'fingerstyle', 'independencia-mao-direita'],
    contexts: ['estudar-tecnica', 'bosses'],
    prerequisites: ['blackbird'],
    nextSongs: [],
    bestVersion: { label: 'Andy McKee (CandyRat)', url: 'https://www.youtube.com/results?search_query=andy+mckee+drifting' },
    bestLesson: { label: 'Aula / tablatura', url: 'https://www.youtube.com/results?search_query=andy+mckee+drifting+tutorial' },
    notes: 'O grande boss da técnica moderna: percussão, tapping e harmônicos ao mesmo tempo. Objetivo de horizonte — cada pedaço aprendido já é vitória.',
  },
  {
    id: 'cavatina',
    title: 'Cavatina',
    artist: 'Stanley Myers',
    difficulty: 5,
    status: 'quero-aprender',
    techniques: ['fingerstyle', 'independencia-mao-direita', 'voicings'],
    contexts: ['relaxar', 'bosses', 'estudar-tecnica'],
    prerequisites: ['tears-in-heaven'],
    nextSongs: [],
    bestVersion: { label: 'John Williams', url: 'https://www.youtube.com/results?search_query=john+williams+cavatina' },
    bestLesson: { label: 'Aula (clássico)', url: 'https://www.youtube.com/results?search_query=cavatina+guitar+lesson' },
    notes: 'Beleza pura, exigência técnica alta. Tema de "O Franco Atirador". Uma música para uma vida inteira de refino.',
  },
]
